name: (DEMO) HeroDevs EOL Scan With Docker Image

on:
  workflow_dispatch: {}

env:
  TRACKING_OPT_OUT: 'true'

jobs:
  scan:
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run EOL Scan
        run: |
          docker run --name eol-scanner \
            -v $GITHUB_WORKSPACE:/app \
            -w /app \
            ghcr.io/herodevs/eol-scan --save --output /tmp/herodevs.report.json
          docker cp eol-scanner:/tmp/herodevs.report.json ${{ runner.temp }}/herodevs.report.json
          docker rm eol-scanner

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: my-eol-report
          path: ${{ runner.temp }}/herodevs.report.json
