name: (DEMO) HeroDevs EOL Scan NPX

on:
  workflow_dispatch: {}
  push:
    branches:
      - 'chore/debug_file_warning'

env:
  TRACKING_OPT_OUT: 'true'
  NODE_OPTIONS: '--trace-warnings'

jobs:
  scan:
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Run EOL Scan
        run: npx @herodevs/cli@beta scan eol --save

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: my-eol-report
          path: ./herodevs.report.json
